name: Create and Upload Zip

on:
  push:
    branches:
      - main

jobs:
  zip-folder:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create a zip of the resource-pack folder content
      run: |
        # Folder to be zipped
        FOLDER="resource-pack"

        # Create the zip file with only the folder's content
        cd $FOLDER
        zip -r ../resource-pack.zip .
        cd ..
    
    - name: Check if the zip file has changed
      id: check_diff
      run: |
        if [[ -f resource-pack.zip ]] && git ls-files --error-unmatch resource-pack.zip > /dev/null 2>&1; then
          if git show HEAD:resource-pack.zip | cmp -s - resource-pack.zip; then
            echo "No changes to the zip file. Skipping commit and push."
            echo "changed=false" >> $GITHUB_OUTPUT
            exit 0
          fi
        fi
        echo "changed=true" >> $GITHUB_OUTPUT

    - name: Commit and push the zip file to the repository
      if: steps.check_diff.outputs.changed == 'true'
      run: |
        # Configure git with username and email
        git config --global user.name "${{ secrets.CI_USER_NAME || 'github-actions' }}"
        git config --global user.email "${{ secrets.CI_USER_EMAIL || 'github-actions[bot]@users.noreply.github.com' }}"

        # Set the correct remote URL with token
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

        # Add the zip file to the repository
        git add resource-pack.zip
        git commit -m "Add/Update resource-pack.zip"
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
